package com.stm.bledemo.ble

data class BLEResult(
    val id: String,
    val value: ByteArray?,
    val status: Int
) {
    // AutoGenerated OverRide Functions for ByteArray
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as BLEResult

        if (id != other.id) return false
        if (value != null) {
            if (other.value == null) return false
            if (!value.contentEquals(other.value)) return false
        } else if (other.value != null) return false
        if (status != other.status) return false

        return true
    }

    override fun hashCode(): Int {
        var result = id.hashCode()
        result = 31 * result + (value?.contentHashCode() ?: 0)
        result = 31 * result + status
        return result
    }
}
